### ISSUE TITLE
List Signature

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/ITI.DSGj#25]
### Section Number

general

### What is wrong

I was wandering if we should give guidance also regarding the List Signature when DSG it is used with MHDS...

### Priority

{"High"=>"Important issue where there is major issue to be resolved. Requires discussion and debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by JohnMoehrke** [comment]
SubmissionSet signature is being considered. We chose to not support it in first draft due to time constraints, and understanding of the SubmissionSet signature.

A SubmissionSet signature is not tied to the XDS SubmissionSet object, nor would it be tied to the MHD use of FHIR List. The only portion of the SubmissionSet that is preserved in the signature is the SubmissionSet uniqueId, which MHD requires as well. So, the support for SubmissionSet is agnostic to XDS vs MHD.
